logging:
  config: classpath:logback.xml

server:
  port: 8081

spring:
  application:
    name: doudou-agent
  main:
    allow-bean-definition-overriding: true

  config:
    import:
      - classpath:nacos_config.yml
      - nacos:@profiles.active@.yaml
      - nacos:redis.yaml
      - nacos:datasource-doudou.yaml

fons4cloud:
  upload:
    oss:
      enabled: true
      provider: minio
      secret-id: xxxxxx
      secret-key: xxxxx
      bucket: doudou
      endpoint: xxxxx


  freemarker:
    template-loader-path:
      - classpath:/template/
    suffix: .ftl
  mvc:
    static-path-pattern: /static/*



