logging:
  config: classpath:logback.xml

server:
  port: 8081

spring:
  application:
    name: doudou-agent
  main:
    allow-bean-definition-overriding: true
  config:
    import:
      - classpath:nacos_config.yml
      - nacos:@profiles.active@.yaml
      - nacos:datasource-doudou.yaml
      - nacos:redis.yaml
  ai:
    openai:
      api-key: ${dashscope.key}
      base-url: https://dashscope.aliyuncs.com/compatible-mode/
      chat:
        options:
          model: deepseek-v4-flash
          temperature: 0.7
      embedding:
        api-key: ${dashscope.key}
        base-url:  https://dashscope.aliyuncs.com/compatible-mode/
        options:
          model: text-embedding-v4
          dimmension: 1024

sys:
  tavily:
    api-key: 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  # 记得改成你自己的
    mcp-url: https://mcp.tavily.com/mcp/


fons4cloud:
  upload:
    oss:
      enabled: true
      provider: minio
      secret-id: xxxxxx
      secret-key: xxxxx
      bucket: doudou
      endpoint: xxxxx


  freemarker:
    template-loader-path:
      - classpath:/template/
    suffix: .ftl
  mvc:
    static-path-pattern: /static/*



