<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0"
         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>
    <parent>
        <groupId>com.fons.cloud.ai</groupId>
        <artifactId>fons4ai-app</artifactId>
        <version>${revision}</version>
        <relativePath>../pom.xml</relativePath>
    </parent>

    <description>仿豆包AGENT</description>
    <artifactId>fons4ai-app-doudou-agent</artifactId>


    <dependencies>
        <dependency>
            <groupId>com.fons.cloud</groupId>
            <artifactId>fons4cloud-nacos-starter</artifactId>
            <version>${revision}</version>
        </dependency>

        <dependency>
            <groupId>com.fons.cloud</groupId>
            <artifactId>fons4cloud-dubbo-starter</artifactId>
            <version>${revision}</version>
        </dependency>

        <dependency>
            <groupId>com.fons.cloud</groupId>
            <artifactId>fons4cloud-common-db-datasource</artifactId>
            <version>${revision}</version>
        </dependency>

        <dependency>
            <groupId>com.fons.cloud</groupId>
            <artifactId>fons4cloud-common-web</artifactId>
            <version>${revision}</version>
        </dependency>

        <dependency>
            <groupId>com.fons.cloud</groupId>
            <artifactId>fons4cloud-common-file</artifactId>
            <version>${revision}</version>
        </dependency>

        <dependency>
            <groupId>com.fons.cloud.ai</groupId>
            <artifactId>fons4ai-agent-spring-ai-starter</artifactId>
            <version>${revision}</version>
        </dependency>

        <dependency>
            <groupId>com.fons.cloud.ai</groupId>
            <artifactId>fons4ai-rag-spring-ai-starter</artifactId>
            <version>${revision}</version>
        </dependency>
    </dependencies>


</project>